apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app-deployment
  labels:
    app: earthquake-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: earthquake-service
  template:
    metadata:
      labels:
        app: earthquake-service
    spec:
      containers:
      - name: earthquake-service
        image: ghcr.io/arturgoms/earthquake-service:1.0.0
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: app-config
        env:
          - name: STARTUP
            value: "APP"
          - name: DATABASE_URL
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: DATABASE_URL
        ports:
          - containerPort: 80
            name: gunicorn
      imagePullSecrets:
        - name: dockerconfigjson-github-com
---

apiVersion: v1
kind: Service
metadata:
  name: django-cluster-ip-service
spec:
  type: NodePort
  selector:
    app: earthquake-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31000
